server.port=8081
spring.application.name=eats-service


spring.data.mongodb.uri=mongodb://localhost:27017/eats_db

spring.kafka.bootstrap-servers=localhost:9092

minio.endpoint=http://localhost:9000
minio.accessKey=minioadmin
minio.secretKey=minioadmin
minio.bucket=eats-images

logging.level.com.uber.eats=INFO
